title: Ahmed Baruwa
name: Ahmed Baruwa
email: aobaruwa@gmail.com
url: https://aobaruwa.github.io/
tagline: artificial intelligence research, tech + society and miscellaneous.
github: aobaruwa
twitter: 
  username: aobaruwa
social:
  name: Ahmed Baruwa
  links:
    - https://twitter.com/aobaruwa
    - https://www.linkedin.com/in/ahmedbaruwa/
    - https://github.com/aobaruwa

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title
excerpt_separator: "<!--excerpt-->"
